#pragma once

// synth_runtime::ShellComponent / SYNTH_RUNTIME_MAIN — the generic JUCE
// window chrome that wraps a synth_runtime::Runtime<App> (Task 2) and its
// MidiPanel (Task 3) into a runnable application (Plan 3 Task 4).
//
// ShellComponent hosts, top to bottom:
//   - a patch-command row (New/Save/Save As/Load/Revert), wired straight to
//     Runtime's patch methods; Save As and Load open a juce::FileChooser
//     rooted at Runtime::GetEngine().Config().patchesRoot (launched async,
//     per modern JUCE idiom — see FileChooser::launchAsync's docs: the
//     chooser must outlive the async operation, so it's held in a
//     member unique_ptr recreated on each launch)
//   - the MidiPanel (Task 3)
//   - the AudioPanel (Plan 4 Task 3): output-device combo + status label
//   - a status label reflecting the last patch command's result
//   - the app's own UIComponent(), filling the remainder of the window
//
// Runtime's timer-driven repaint hook (Runtime::Start() calls it at the end
// of every tick) is wired to repaint both the shell chrome and the app
// component, so app UI redraws stay driven by the same single timer as the
// engine's message-thread tick.
//
// SYNTH_RUNTIME_MAIN(AppType) expands to a full juce::JUCEApplication
// wrapper (ShellApplication<AppType>) plus a START_JUCE_APPLICATION
// instantiation. JUCE_CREATE_APPLICATION_DEFINE(AppClass) (see
// juce_Initialisation.h) substitutes AppClass verbatim into `new AppClass()`
// with no macro-argument splitting, so passing a template-id like
// synth_runtime::ShellApplication<AppType> through START_JUCE_APPLICATION
// works directly; no per-app subclass needs to be generated by the macro.

#include "synth/AppConcepts.hpp"
#include "synth/AppContext.hpp"
#include "synth/PatchPersistence.hpp"
#include "synth/ThreadId.hpp"

#include "MidiPanel.hpp"
#include "Runtime.hpp"

#include <juce_gui_extra/juce_gui_extra.h>

#include <exception>
#include <memory>

namespace synth_runtime {

template <synth::SynthApplication App>
class ShellComponent : public juce::Component {
public:
    explicit ShellComponent(Runtime<App>& runtime) : runtime_(runtime) {
        newButton_.setButtonText("New");
        newButton_.onClick = [this] { runtime_.NewPatch(); };
        addAndMakeVisible(newButton_);

        saveButton_.setButtonText("Save");
        saveButton_.onClick = [this] { runtime_.SavePatch(); };
        addAndMakeVisible(saveButton_);

        saveAsButton_.setButtonText("Save As");
        saveAsButton_.onClick = [this] { LaunchSaveAsChooser(); };
        addAndMakeVisible(saveAsButton_);

        loadButton_.setButtonText("Load");
        loadButton_.onClick = [this] { LaunchLoadChooser(); };
        addAndMakeVisible(loadButton_);

        revertButton_.setButtonText("Revert");
        revertButton_.onClick = [this] { runtime_.RevertPatch(); };
        addAndMakeVisible(revertButton_);

        statusLabel_.setColour(juce::Label::textColourId, juce::Colours::white);
        statusLabel_.setJustificationType(juce::Justification::centredLeft);
        statusLabel_.setText("Ready", juce::dontSendNotification);
        addAndMakeVisible(statusLabel_);

        addAndMakeVisible(runtime_.MidiPanelComponent());
        addAndMakeVisible(runtime_.AudioPanelComponent());
        addAndMakeVisible(runtime_.AppComponent());
    }

    // Called by Runtime's timer-driven repaint hook (wired in the
    // application wrapper's initialise(), after Start()) once per UI frame.
    void RepaintAll() {
        repaint();
        runtime_.MidiPanelComponent().repaint();
        runtime_.AudioPanelComponent().repaint();
        runtime_.AppComponent().repaint();
    }

    void resized() override {
        auto area = getLocalBounds();

        auto patchRow = area.removeFromTop(36);
        const int patchButtonWidth = 84;
        newButton_.setBounds(patchRow.removeFromLeft(patchButtonWidth).reduced(4));
        saveButton_.setBounds(patchRow.removeFromLeft(patchButtonWidth).reduced(4));
        saveAsButton_.setBounds(patchRow.removeFromLeft(patchButtonWidth).reduced(4));
        loadButton_.setBounds(patchRow.removeFromLeft(patchButtonWidth).reduced(4));
        revertButton_.setBounds(patchRow.removeFromLeft(patchButtonWidth).reduced(4));
        statusLabel_.setBounds(patchRow.reduced(4));

        runtime_.MidiPanelComponent().setBounds(area.removeFromTop(56));
        runtime_.AudioPanelComponent().setBounds(area.removeFromTop(32));

        runtime_.AppComponent().setBounds(area);
    }

private:
    void SetStatus(const juce::String& text) { statusLabel_.setText(text, juce::dontSendNotification); }

    void LaunchSaveAsChooser() {
        const juce::File root(runtime_.GetEngine().Config().patchesRoot.string());
        fileChooser_ = std::make_unique<juce::FileChooser>("Save Patch As", root);
        const auto flags = juce::FileBrowserComponent::saveMode | juce::FileBrowserComponent::canSelectDirectories |
                            juce::FileBrowserComponent::warnAboutOverwriting;
        fileChooser_->launchAsync(flags, [this](const juce::FileChooser& chooser) {
            const juce::File result = chooser.getResult();
            if (result == juce::File{}) {
                return;
            }
            runtime_.SavePatchAs(result);
            SetStatus("Save As requested: " + result.getFullPathName());
        });
    }

    void LaunchLoadChooser() {
        const juce::File root(runtime_.GetEngine().Config().patchesRoot.string());
        fileChooser_ = std::make_unique<juce::FileChooser>("Load Patch", root);
        const auto flags = juce::FileBrowserComponent::openMode | juce::FileBrowserComponent::canSelectDirectories;
        fileChooser_->launchAsync(flags, [this](const juce::FileChooser& chooser) {
            const juce::File result = chooser.getResult();
            if (result == juce::File{}) {
                return;
            }
            runtime_.LoadPatch(result);
            SetStatus("Load requested: " + result.getFullPathName());
        });
    }

    Runtime<App>& runtime_;

    juce::TextButton newButton_;
    juce::TextButton saveButton_;
    juce::TextButton saveAsButton_;
    juce::TextButton loadButton_;
    juce::TextButton revertButton_;
    juce::Label statusLabel_;

    // Held so the chooser survives until its async callback fires (modern
    // JUCE idiom: FileChooser::launchAsync requires the chooser object to
    // stay alive for the duration of the operation). Recreated on each
    // launch, which destroys any previous (already-completed) chooser.
    std::unique_ptr<juce::FileChooser> fileChooser_;
};

// The application wrapper instantiated by SYNTH_RUNTIME_MAIN(AppType). Owns
// the Runtime<App> and the top-level window, in construction/destruction
// order (window before runtime is destroyed, per shutdown() below).
template <synth::SynthApplication App>
class ShellApplication : public juce::JUCEApplication {
public:
    const juce::String getApplicationName() override { return juce::String(App::Config().appName); }
    const juce::String getApplicationVersion() override { return "0.1"; }
    bool moreThanOneInstanceAllowed() override { return true; }

    void initialise(const juce::String&) override {
        synth::SetCurrentThreadId(synth::ThreadId::Message);

        // JUCE does not wrap initialise() in a try/catch, so an exception
        // here would unwind straight out of the framework's call site and
        // abort the process uncleanly. Catch, log, and fail the launch
        // instead, tearing down any partially constructed members in the
        // same safe order used by shutdown() below.
        try {
            runtime_ = std::make_unique<Runtime<App>>();
            runtime_->Start();

            const synth::RuntimeConfig config = App::Config();
            window_ = std::make_unique<MainWindow>(juce::String(config.appName), config.uiWidth, config.uiHeight,
                                                   *runtime_);
        } catch (const std::exception& e) {
            INFO("ShellApplication::initialise failed: %s", e.what());
            if (runtime_) {
                runtime_->SetRepaintHook({});
            }
            window_.reset();
            runtime_.reset();
            setApplicationReturnValue(1);
            quit();
        }
    }

    void shutdown() override {
        // The runtime's timer-driven repaint hook captures the ShellComponent
        // owned by window_. Clear the hook (and anything else referencing
        // shell state) BEFORE window_.reset() destroys that component, so
        // the timer can never fire into a dangling pointer between the two
        // resets. Only then destroy the window, followed by the runtime
        // itself, so no component outlives the Runtime it references.
        if (runtime_) {
            runtime_->SetRepaintHook({});
        }
        window_.reset();
        runtime_.reset();
    }

    void systemRequestedQuit() override { quit(); }
    void anotherInstanceStarted(const juce::String&) override {}

private:
    class MainWindow final : public juce::DocumentWindow {
    public:
        MainWindow(juce::String name, int width, int height, Runtime<App>& runtime)
            : DocumentWindow(std::move(name), juce::Colours::black, DocumentWindow::allButtons) {
            setUsingNativeTitleBar(true);
            auto* shell = new ShellComponent<App>(runtime);
            setContentOwned(shell, false);
            setSize(width, height);
            centreWithSize(width, height);
            setVisible(true);
            runtime.SetRepaintHook([shell] { shell->RepaintAll(); });
        }

        void closeButtonPressed() override { juce::JUCEApplication::getInstance()->systemRequestedQuit(); }
    };

    std::unique_ptr<Runtime<App>> runtime_;
    std::unique_ptr<MainWindow> window_;
};

}  // namespace synth_runtime

#define SYNTH_RUNTIME_MAIN(AppType) START_JUCE_APPLICATION(synth_runtime::ShellApplication<AppType>)
