#pragma once

// synth_runtime::ShellComponent / SYNTH_RUNTIME_MAIN — the generic JUCE
// window chrome that wraps a synth_runtime::Runtime<App> (Task 2) into a
// runnable application (Plan 3 Task 4).
//
// ShellComponent is a thin MainPane<App> host (Plan 4 Task 2, sru-1): it
// constructs a single MainPane<App>, `addAndMakeVisible`s it, and its
// resized() fills the shell's full bounds with it. The former patch-command
// row (New/Save/Save As/Load/Revert + patch name + status label), the
// MidiPanel strip, and the AudioPanel strip are gone from this layout --
// MainPane's sidebar (Audio/Controllers/File) and content host are the only
// chrome now. As of Task 3 of Plan 4, MainPane's Audio and File pages
// (AudioConfigPage.hpp / FilePage.hpp) are real, re-homing AudioPanel's and
// the old patch-command row's logic respectively (AudioPanel itself was
// deleted from MidiPanel.hpp this task); Controllers remains a placeholder
// until the next task lands ControllersPage. MidiPanelComponent()
// (Runtime.hpp) still constructs that component, just unparented from the
// shell, until ControllersPage re-homes its logic too.
//
// Runtime's timer-driven repaint hook (Runtime::Start() calls it at the end
// of every tick) is wired to repaint the shell, which now just means
// refreshing and repainting the MainPane (which itself refreshes/repaints
// its sidebar and whichever of {app component, open page} is currently
// visible -- see MainPane::RefreshOnTick's doc comment for why every page
// gets refreshed regardless of visibility).
//
// SYNTH_RUNTIME_MAIN(AppType) expands to a full juce::JUCEApplication
// wrapper (ShellApplication<AppType>) plus a START_JUCE_APPLICATION
// instantiation. JUCE_CREATE_APPLICATION_DEFINE(AppClass) (see
// juce_Initialisation.h) substitutes AppClass verbatim into `new AppClass()`
// with no macro-argument splitting, so passing a template-id like
// synth_runtime::ShellApplication<AppType> through START_JUCE_APPLICATION
// works directly; no per-app subclass needs to be generated by the macro.

#include "synth/AppConcepts.hpp"
#include "synth/AppContext.hpp"
#include "synth/PatchPersistence.hpp"
#include "synth/ThreadId.hpp"

#include "MainPane.hpp"
#include "MidiPanel.hpp"
#include "Runtime.hpp"

#include <juce_gui_extra/juce_gui_extra.h>

#include <exception>
#include <memory>

namespace synth_runtime {

template <synth::SynthApplication App>
class ShellComponent : public juce::Component {
public:
    explicit ShellComponent(Runtime<App>& runtime) : runtime_(runtime), mainPane_(runtime) {
        addAndMakeVisible(mainPane_);
    }

    // Called by Runtime's timer-driven repaint hook (wired in the
    // application wrapper's initialise(), after Start()) once per UI frame.
    // Writes this tick's deadline sample (sru-2 binding) before repainting,
    // so the sidebar's rolling-max label is always current by the time this
    // hook's repaint takes effect.
    void RepaintAll() {
        mainPane_.WriteDeadlineSample(runtime_.DeadlineSamplePct());
        mainPane_.RefreshOnTick();
        mainPane_.repaint();
    }

    void resized() override { mainPane_.setBounds(getLocalBounds()); }

    MainPane<App>& GetMainPane() { return mainPane_; }

private:
    Runtime<App>& runtime_;
    MainPane<App> mainPane_;
};

// The application wrapper instantiated by SYNTH_RUNTIME_MAIN(AppType). Owns
// the Runtime<App> and the top-level window, in construction/destruction
// order (window before runtime is destroyed, per shutdown() below).
template <synth::SynthApplication App>
class ShellApplication : public juce::JUCEApplication {
public:
    const juce::String getApplicationName() override { return juce::String(App::Config().appName); }
    const juce::String getApplicationVersion() override { return "0.1"; }
    bool moreThanOneInstanceAllowed() override { return true; }

    void initialise(const juce::String&) override {
        synth::SetCurrentThreadId(synth::ThreadId::Message);

        // JUCE does not wrap initialise() in a try/catch, so an exception
        // here would unwind straight out of the framework's call site and
        // abort the process uncleanly. Catch, log, and fail the launch
        // instead, tearing down any partially constructed members in the
        // same safe order used by shutdown() below.
        try {
            runtime_ = std::make_unique<Runtime<App>>();
            runtime_->Start();

            const synth::RuntimeConfig config = App::Config();
            window_ = std::make_unique<MainWindow>(juce::String(config.appName), config.uiWidth, config.uiHeight,
                                                   *runtime_);
        } catch (const std::exception& e) {
            INFO("ShellApplication::initialise failed: %s", e.what());
            if (runtime_) {
                runtime_->SetRepaintHook({});
            }
            window_.reset();
            runtime_.reset();
            setApplicationReturnValue(1);
            quit();
        }
    }

    void shutdown() override {
        // The runtime's timer-driven repaint hook captures the ShellComponent
        // owned by window_. Clear the hook (and anything else referencing
        // shell state) BEFORE window_.reset() destroys that component, so
        // the timer can never fire into a dangling pointer between the two
        // resets. Only then destroy the window, followed by the runtime
        // itself, so no component outlives the Runtime it references.
        if (runtime_) {
            runtime_->SetRepaintHook({});
        }
        window_.reset();
        runtime_.reset();
    }

    void systemRequestedQuit() override { quit(); }
    void anotherInstanceStarted(const juce::String&) override {}

private:
    class MainWindow final : public juce::DocumentWindow {
    public:
        MainWindow(juce::String name, int width, int height, Runtime<App>& runtime)
            : DocumentWindow(std::move(name), juce::Colours::black, DocumentWindow::allButtons) {
            setUsingNativeTitleBar(true);
            auto* shell = new ShellComponent<App>(runtime);
            setContentOwned(shell, false);
            setSize(width, height);
            centreWithSize(width, height);
            setVisible(true);
            runtime.SetRepaintHook([shell] { shell->RepaintAll(); });
        }

        void closeButtonPressed() override { juce::JUCEApplication::getInstance()->systemRequestedQuit(); }
    };

    std::unique_ptr<Runtime<App>> runtime_;
    std::unique_ptr<MainWindow> window_;
};

}  // namespace synth_runtime

#define SYNTH_RUNTIME_MAIN(AppType) START_JUCE_APPLICATION(synth_runtime::ShellApplication<AppType>)
