.PHONY: all build test install check clean

all: check

build: check

test: check

install:
	python3 scripts/install.py install

check:
	python3 scripts/install.py check

clean:
	python3 scripts/install.py clean
